### ISSUE TITLE
개발 할 것 정리

### ISSUE THREAD

**Issue by leechoongyon** [leechoongyon/coupon-issuance#21]
- [x] 발급 요청 API mapstruct 적용 #20 
- [ ] Redis Sorted Set 저장 #17 
- [x] redis docker 띄우기 #16
